/*
 * Copyright 2009 Phil Burk, Mobileer Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.softsynth.ksyn.unitgen

import com.softsynth.ksyn.Synthesizer
import com.softsynth.ksyn.ports.UnitInputPort
import com.softsynth.ksyn.ports.UnitOutputPort
import com.softsynth.ksyn.toSample
import com.softsynth.ksyn.util.PseudoRandom

/**
 * Random output with 3dB per octave rolloff providing a soft natural noise sound. Generated using
 * Gardner method. Optimization suggested by James McCartney uses a tree to select which random
 * value to replace.
 * 
 * <pre>
 *  x x x x x x x x x x x x x x x x 
 *  x   x   x   x   x   x   x   x   
 *  x       x       x       x       
 *  x               x               
 *  x
 * </pre>
 * 
 * Tree is generated by counting trailing zeros in an increasing index. When the index is zero, no
 * random number is selected.
 * 
 * Author: Phil Burk (C) 1996 SoftSynth.com.
 */
class PinkNoise : UnitGenerator(), UnitSource {

    val amplitude = UnitInputPort("Amplitude", UnitOscillator.DEFAULT_AMPLITUDE)
    val output = UnitOutputPort("Output")

    private val NUM_ROWS = 16
    private val RANDOM_BITS = 24
    private val RANDOM_SHIFT = 32 - RANDOM_BITS

    private val randomNum = PseudoRandom()

    private val rows = IntArray(NUM_ROWS) { 0 }
    private val scalar: Double // used to scale within range of -1.0 to +1.0
    private var runningSum: Int = 0 // used to optimize summing of generators
    private var index: Int = 0 // incremented with each sample
    private val indexMask: Int = (1 shl NUM_ROWS) - 1 // index wrapped and ANDing with this mask

    init {
        addPort(amplitude)
        addPort(output)

        // Calculate maximum possible signed random value. Extra 1 for white
        // noise always added.
        val pmax = (NUM_ROWS + 1) * (1 shl (RANDOM_BITS - 1))
        scalar = 1.0 / pmax
    }

    override fun generate() {
        val amplitudes = amplitude.getValues()
        val outputs = output.getValues()

        for (i in 0 until Synthesizer.FRAMES_PER_BLOCK) {
            outputs[i] = (generatePinkNoise() * amplitudes[i]).toSample()
        }
    }

    fun generatePinkNoise(): Double {
        index = (index + 1) and indexMask

        // If index is zero, don't update any random values.
        if (index != 0) {
            // Determine how many trailing zeros in index.
            // This algorithm will hang if n==0 so test first
            var numZeros = 0
            var n = index

            while ((n and 1) == 0) {
                n = n shr 1
                numZeros++
            }

            // Replace the indexed ROWS random value.
            // Subtract and add back to RunningSum instead of adding all the
            // random values together. Only one changes each time.
            runningSum -= rows[numZeros]
            val newRandom = randomNum.nextRandomInteger() shr RANDOM_SHIFT
            runningSum += newRandom
            rows[numZeros] = newRandom
        }

        // Add extra white noise value.
        val newRandom = randomNum.nextRandomInteger() shr RANDOM_SHIFT
        val sum = runningSum + newRandom

        // Scale to range of -1.0 to 0.9999.
        return scalar * sum
    }

    override fun getOutputPort(): UnitOutputPort {
        return output
    }
}
