/*
 * Copyright 2009 Phil Burk, Mobileer Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.softsynth.ksyn.ports

import com.softsynth.ksyn.engine.SynthesisEngine
import com.softsynth.ksyn.unitgen.UnitGenerator

/**
 * Base class for input and output ports on a UnitGenerator.
 */
abstract class UnitPort(
    var name: String
) {

    var unitGenerator: UnitGenerator? = null
         set(unit: UnitGenerator?) {
             // If a port is in a circuit then we want to just use the lower level
             // unit that instantiated the circuit.
             if (field == null) {
                 field = unit
             }
         }

    /**
     * This is the last value calculated for the port.
     * For an input, it's the value fed into the unit.
     * For an output, it's the value generated by the unit.
     */
    open var value: Double = 0.0
        set(value: Double)  { field = value }
        get() = field


    /**
     * A default constant value. For an input, this is used when nothing is connected.
     */
    var constant: Double = 0.0

    /**
     * The number of internal parts this port has.
     * Defaults to 1 for simple ports.
     */
    open val numParts: Int
        get() = 1


    fun getSynthesisEngine(): SynthesisEngine? = unitGenerator?.synthesisEngine

    /**
     * Schedule a task to run at a specific time.
     * @param time The time in seconds (or ticks) to execute.
     * @param command The lambda block to execute.
     */
    fun scheduleCommand(time: Double, command: () -> Unit) {
        // Navigate up to the Engine: Port -> UnitGenerator -> Engine
        val engine = unitGenerator?.synthesisEngine

        if (engine == null) {
            // If not connected to an engine, run immediately (fallback behavior)
            command()
        } else {
            // Delegate to the engine's scheduler
            engine.scheduleCommand(time, command)
        }
    }

    /**
    * Queue a task to run ASAP.
    * @param command The lambda block to execute.
    */
    fun queueCommand(command: () -> Unit) {
        // Navigate up to the Engine: Port -> UnitGenerator -> Engine
        val engine = unitGenerator?.synthesisEngine

        if (engine == null) {
            // If not connected to an engine, run immediately (fallback behavior)
            command()
        } else {
            // Delegate to the engine's scheduler
            engine.queueCommand(command)
        }
    }
}
