package com.softsynth.ksyn.math

/**
 * PolynomialTableData<br>
 * Provides an array of double[] containing data generated by a polynomial.<br>
 * This is typically used with ChebyshevPolynomial. Input to Polynomial is -1..1, output is -1..1.
 *
 * @author Nick Didkovsky (C) 1997 Phil Burk and Nick Didkovsky
 * @see ChebyshevPolynomial
 * @see Polynomial
 */
class PolynomialTableData(polynomial: Polynomial, numFrames: Int) {
    val data: DoubleArray = DoubleArray(numFrames)
    private val polynomial: Polynomial = polynomial

    init {
        buildData()
    }

    private fun buildData() {
        val xInterval = 2.0 / (data.size - 1) // FIXED, added "- 1"
        var x: Double
        for (i in data.indices) {
            x = i * xInterval - 1.0
            data[i] = polynomial.evaluate(x)
            // LOGGER.debug("x = " + x + ", p(x) = " + data[i] );
        }
    }
}
